name: 'Deploy Docs (PR)'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

env:
  PR_NUMBER: ${{ github.event.number }}

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    name: Build Docusaurus and Storybook and deploy PR preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Check if docs is affected
        id: docs
        shell: bash
        run: |
          if npx nx show projects --affected | grep -q docs; then
            echo "affected=true" >> "$GITHUB_OUTPUT"
          else
            echo "affected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies
        if: github.event.action != 'closed' && steps.docs.outputs.affected == 'true'
        run: npm ci

      - name: Lint, test and build website
        if: github.event.action != 'closed' && steps.docs.outputs.affected == 'true'
        run: npx nx run-many -t lint,test,build --projects=docs

      - name: Build storybook
        if: github.event.action != 'closed' && steps.docs.outputs.affected == 'true'
        run: npx nx run storybook:build:ci

      - name: Deploy preview
        if: steps.docs.outputs.affected == 'true'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/docs
          pages-base-url: 'designsystem.migrationsverket.se'
