name: 'PR Checks'

env:
  HUSKY: 0

on:
  pull_request:
    types:
      - opened
      - labeled
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Lint, test and build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Check if Storybook is affected
        id: storybook
        shell: bash
        run: |
          if npx nx show projects --affected | grep -q storybook; then
            echo "affected=true" >> "$GITHUB_OUTPUT"
          else
            echo "affected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install Playwright
        if: >
          steps.storybook.outputs.affected == 'true' && (github.event.action == 'labeled' && github.event.label && (github.event.label.name == 'test' || github.event.label.name == 'a11y')) ||
          steps.storybook.outputs.affected == 'true' && (contains(github.event.pull_request.labels.*.name, 'test') || contains(github.event.pull_request.labels.*.name, 'a11y'))
        run: npx playwright install chromium --only-shell

      - name: Build packages
        run: npx nx affected -t lint stylelint build

      - name: Test packages
        if: >
          (github.event.action == 'labeled' && github.event.label && github.event.label.name == 'test') ||
          contains(github.event.pull_request.labels.*.name, 'test')
        run: npx nx affected -t test

      - name: A11y check packages
        if: >
          steps.storybook.outputs.affected == 'true' && (github.event.action == 'labeled' && github.event.label && github.event.label.name == 'a11y') ||
          steps.storybook.outputs.affected == 'true' && contains(github.event.pull_request.labels.*.name, 'a11y')
        run: npx nx run-many -t a11y-dark-mode a11y-forced-colors -p storybook --parallel=1
